name: malicious-action
description: Malicious Action for demos
inputs:
  example:
    description: example
    required: false
    default: 'false'
runs:
  using: docker
  image: docker://cycodelabs/malicious-image:latest